#!/usr/bin/env bash
set -e

BASEDIR="$(cd "$(dirname "$0")" && pwd)"
cd "$BASEDIR"

git -C dotbot pull origin master || true
"$BASEDIR/dotbot/bin/dotbot" -d "$BASEDIR" -p "$BASEDIR/dotbot-winget/winget.py" -c install.conf.yaml "$@"
