syntax on
set number
set hlsearch
set incsearch
set ignorecase
set smartcase
set autoindent
set tabstop=2
set shiftwidth=2
set expandtab
set mouse=a
set cursorline
set scrolloff=8
set backspace=indent,eol,start
set laststatus=2
set ruler
set showcmd
set wildmenu
set noswapfile
